[project]
name = "fastapi-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Stas"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
